export const exerciseSeeds = [
  { name: "Bench Press", category: "Chest", isCompound: true, includeBodyWeightInVolume: false },
  { name: "Incline Bench Press", category: "Chest", isCompound: true, includeBodyWeightInVolume: false },
  { name: "Squat", category: "Legs", isCompound: true, includeBodyWeightInVolume: false },
  { name: "Back Squat", category: "Legs", isCompound: true, includeBodyWeightInVolume: false },
  { name: "Deadlift", category: "Back", isCompound: true, includeBodyWeightInVolume: false },
  { name: "Romanian Deadlift", category: "Legs", isCompound: true, includeBodyWeightInVolume: false },
  { name: "Overhead Press", category: "Shoulders", isCompound: true, includeBodyWeightInVolume: false },
  { name: "Pull-Up", category: "Back", isCompound: true, includeBodyWeightInVolume: true },
  { name: "Barbell Row", category: "Back", isCompound: true, includeBodyWeightInVolume: false },
  { name: "Lat Pulldown", category: "Back", isCompound: false, includeBodyWeightInVolume: false },
  { name: "Leg Press", category: "Legs", isCompound: false, includeBodyWeightInVolume: false },
  { name: "Biceps Curl (Barbell)", category: "Arms", isCompound: false, includeBodyWeightInVolume: false },
  { name: "Dumbbell Curl", category: "Arms", isCompound: false, includeBodyWeightInVolume: false },
  { name: "Triceps Rope Pushdown", category: "Arms", isCompound: false, includeBodyWeightInVolume: false },
  { name: "Triceps Pushdown", category: "Arms", isCompound: false, includeBodyWeightInVolume: false },
  { name: "Lateral Raise", category: "Shoulders", isCompound: false, includeBodyWeightInVolume: false },
  { name: "Weighted Dips", category: "Chest", isCompound: true, includeBodyWeightInVolume: true },
  { name: "Weighted Sit-Up", category: "Core", isCompound: false, includeBodyWeightInVolume: true },
  { name: "Plank (Minutes)", category: "Core", isCompound: false, includeBodyWeightInVolume: true }
] as const;
