export const exerciseSeeds = [
  { name: "Bench Press", category: "Chest", isCompound: true, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Incline Bench Press", category: "Chest", isCompound: true, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Squat", category: "Legs", isCompound: true, includeBodyWeightInVolume: true, bodyWeightVolumeMultiplier: 0.7 },
  { name: "Back Squat", category: "Legs", isCompound: true, includeBodyWeightInVolume: true, bodyWeightVolumeMultiplier: 0.7 },
  { name: "Deadlift", category: "Back", isCompound: true, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Romanian Deadlift", category: "Legs", isCompound: true, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Overhead Press", category: "Shoulders", isCompound: true, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Pull-Up", category: "Back", isCompound: true, includeBodyWeightInVolume: true, bodyWeightVolumeMultiplier: 1 },
  { name: "Chin-Up", category: "Back", isCompound: true, includeBodyWeightInVolume: true, bodyWeightVolumeMultiplier: 1 },
  { name: "Barbell Row", category: "Back", isCompound: true, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Lat Pulldown", category: "Back", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Leg Press", category: "Legs", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Leg Extension", category: "Legs", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Leg curl (lying)", category: "Legs", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Butterfly", category: "Chest", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Biceps Curl (Barbell)", category: "Arms", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Dumbbell Curl", category: "Arms", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Triceps Rope Pushdown", category: "Arms", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Triceps Pushdown", category: "Arms", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Lateral Raise", category: "Shoulders", isCompound: false, includeBodyWeightInVolume: false, bodyWeightVolumeMultiplier: 1 },
  { name: "Weighted Dips", category: "Chest", isCompound: true, includeBodyWeightInVolume: true, bodyWeightVolumeMultiplier: 1 },
  { name: "Weighted Sit-Up", category: "Core", isCompound: false, includeBodyWeightInVolume: true, bodyWeightVolumeMultiplier: 1 },
  { name: "Plank (Minutes)", category: "Core", isCompound: false, includeBodyWeightInVolume: true, bodyWeightVolumeMultiplier: 1 }
] as const;
